version: 2.1

executors:
  cypress-executor:
    docker:
      - image: cypress/included:13.7.3
    working_directory: ~/project

jobs:
  cypress-run:
    executor: cypress-executor
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm ci
      - run:
          name: Run Cypress API Tests
          command: npx cypress run --spec "cypress/e2e/API/*.js"
      - store_artifacts:
          path: cypress/videos
      - store_artifacts:
          path: cypress/screenshots

workflows:
  version: 2
  test-workflow:
    jobs:
      - cypress-run
